version: "3" # docker-composeのバージョンを指定
services:
  app:
    container_name: system_design_app
    build:
      context: ../../
      dockerfile: ./docker/local/java/Dockerfile
    working_dir: /app
    volumes:
      - ../../../sys-design-dev:/app:cached
    environment:
      JAVA_ENV: development
    ports:
      - "8080:8080"
    privileged: true
    tty: true
    command: >
      sh -c '
          ./gradlew
          wait-for-it.sh system_design_db:3306 --timeout=30 -- ./gradlew tomcatRun
      '
    networks:
      - system_design-network

  mysql:
    container_name: system_design_db
    platform: linux/x86_64
    build:
      context: ../../
      dockerfile: ./docker/local/mysql/Dockerfile
    ports:
      - "3306:3306"
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --default-authentication-plugin=mysql_native_password
    environment:
      TZ: "Asia/Tokyo"
      MYSQL_DATABASE: db
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - "./mysql/init:/docker-entrypoint-initdb.d"
    networks:
      - system_design-network

  adminer:
    image: adminer:4.6
    container_name: "adminer"
    ports:
      - "8081:8080"
    depends_on:
      - mysql
    networks:
      - system_design-network

networks:
  system_design-network:
    driver: bridge
